# Default values for iotdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

clusterDomain: cluster.local

rpc:
  port: 6667
metric:
  port: 8181
jmx:
  port: 31999

podManagementPolicy: "Parallel"

updateStrategy: RollingUpdate

podAnnotations: {}

imagePullSecrets: []

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

image:
  repository: apache/iotdb
  pullPolicy: IfNotPresent
  tag: 0.12.1-node

serviceAccount:
  create: true
  annotations: {}
  name: ""

env: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  enabled: false
  annotations: {}

nodeSelector: {}

antiAffinity: hard

nodeAffinity: {}

antiAffinityTopologyKey: "kubernetes.io/hostname"

tolerations: []

dataVolumeClaimTemplate: {}
logsVolumeClaimTemplate: {}

rpcService:
  type: ClusterIP
  nodePort: null

metricService:
  type: ClusterIP
  nodePort: null

jmxService:
  type: ClusterIP
  nodePort: null

grafana:
  enable: false
  podAnnotations: []
  config:
    url:
    username:
    password:
  image:
    repository:
    pullPolicy:
    tag:
  imagePullSecrets: []
  tomcat:
    port: 8888
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  resources: {}
  nodeSelector: {}
  nodeAffinity: {}
  tolerations: []
