{{- $fullname := include "iotdb.fullname" . -}}
{{- $releaseNamespace := .Release.Namespace -}}
{{- $clusterDomain := .Values.clusterDomain -}}
{{- $servicePort := int .Values.rpc.port -}}
{{- if (.Files.Glob "files/initdb.d/init.sh") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "iotdb.fullname" . }}-init-db
  labels:
    {{- include "iotdb.labels" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (.Files.Glob "files/initdb.d/init.sh") }}
        initShChecksum: {{ .Files.Get "files/initdb.d/init.sh" | sha256sum | trunc 63 }}
      {{- end }}
      labels:
        {{- include "iotdb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "iotdb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-iotdb
          image: busybox:1.33.1
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'for i in $(seq 1 60); do nc -v -z -w3 {{ include "iotdb.fullname" . }} {{ .Values.rpc.port }} && exit 0 || sleep 5; done; exit 1']
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["/iotdb/initdb.d/init.sh"]
          env:
            - name: host
              value: "{{ printf "%s-%d.%s-headless.%s.svc.%s" $fullname 0 $fullname $releaseNamespace $clusterDomain }}"
            - name: port
              value: "{{ $servicePort }}"
            - name: user
              value: "root"
            - name: password
              value: "iotdb@IVC"
          volumeMounts:
            {{- if (.Files.Glob "files/initdb.d/init.sh") }}
            {{ range $path, $bytes := .Files.Glob "files/initdb.d/init.sh" }}
            - name: iotdb-init-db
              mountPath: {{ print "/iotdb/initdb.d/" ($path | replace "files/initdb.d/" "") }}
              subPath: {{ $path | replace "files/initdb.d/" "" | b64enc | replace "=" "-" }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if (.Files.Glob "files/initdb.d/init.sh") }}
        - name: iotdb-init-db
          configMap:
            name: {{ template "iotdb.fullname" . }}-init-db-cm
        {{- end }}
{{- end }}
