apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotdb.fullname" . }}-metric
  labels:
    {{- include "iotdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricService.type }}
  ports:
    - name: metric
      port: {{ .Values.metric.port }}
      targetPort: {{ .Values.metric.port }}
      {{- if eq .Values.metricService.type "NodePort" }}
      nodePort: {{ .Values.metricService.nodePort }}
      {{- end }}
  selector:
    {{- include "iotdb.selectorLabels" . | nindent 4 }}
