apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotdb.fullname" . }}
  labels:
    {{- include "iotdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rpcService.type }}
  ports:
    - name: rpc
      port: {{ .Values.rpc.port }}
      targetPort: {{ .Values.rpc.port }}
      {{- if eq .Values.rpcService.type "NodePort" }}
      nodePort: {{ .Values.rpcService.nodePort }}
      {{- end }}
  selector:
    {{- include "iotdb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotdb.fullname" . }}-jmx
  labels:
  {{- include "iotdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jmxService.type }}
  ports:
    - name: jmx
      port: {{ .Values.jmx.port }}
      targetPort: {{ .Values.jmx.port }}
      {{- if eq .Values.jmxService.type "NodePort" }}
      nodePort: {{ .Values.jmxService.nodePort }}
      {{- end }}
  selector:
    {{- include "iotdb.selectorLabels" . | nindent 4 }}
