apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "iotdb.fullname" . }}
  labels:
    {{- include "iotdb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iotdb.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "iotdb.fullname" . }}-headless
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (.Files.Glob "files/conf/iotdb-engine.properties") }}
        iotdbEnginePropertiesChecksum: {{ .Files.Get "files/conf/iotdb-engine.properties" | sha256sum | trunc 63 }}
      {{- end }}
      {{- if (.Files.Glob "files/conf/iotdb-env.sh") }}
        iotdbEnvShChecksum: {{ .Files.Get "files/conf/iotdb-env.sh" | sha256sum | trunc 63 }}
      {{- end }}
      {{- if (.Files.Glob "files/ext/udf/ivc-iotdb-udf-0.12.1.jar") }}
        ivcIotdbUdfJarChecksum: {{ .Files.Get "files/ext/udf/ivc-iotdb-udf-0.12.1.jar" | sha256sum | trunc 63 }}
      {{- end }}
      {{- if (.Files.Glob "files/sbin/start-server.sh") }}
        startServerShChecksum: {{ .Files.Get "files/sbin/start-server.sh" | sha256sum | trunc 63 }}
      {{- end }}
      labels:
        {{- include "iotdb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "iotdb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: increase-fd-ulimit
          image: busybox:1.33.1
          command: ["/bin/sh", "-c"]
          args:
            - ulimit -n 65535
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rpc
              containerPort: {{ .Values.rpc.port }}
            - name: jmx
              containerPort: {{ .Values.jmx.port }}
            - name: sync
              containerPort: 5555
            - name: monitor
              containerPort: 8181
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          args:
            - "printgc"
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: 6667
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: 6667
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - mountPath: /iotdb/data
              name: data
            - mountPath: /iotdb/logs
              name: logs
            {{- end }}
            {{- if (.Files.Glob "files/conf/**.properties") }}
            {{ range $path, $bytes := .Files.Glob "files/conf/**.properties" }}
            - name: iotdb-conf-override
              mountPath: {{ print "/iotdb/conf/" ($path | replace "files/conf/" "") }}
              subPath: {{ $path | replace "files/conf/" "" | b64enc | replace "=" "-" }}
            {{- end }}
            {{- end }}
            {{- if (.Files.Glob "files/conf/**.sh") }}
            {{ range $path, $bytes := .Files.Glob "files/conf/**.sh" }}
            - name: iotdb-conf-sh-override
              mountPath: {{ print "/iotdb/conf/" ($path | replace "files/conf/" "") }}
              subPath: {{ $path | replace "files/conf/" "" | b64enc | replace "=" "-" }}
            {{- end }}
            {{- end }}
            {{- if (.Files.Glob "files/ext/udf/**.jar") }}
            {{ range $path, $bytes := .Files.Glob "files/ext/udf/**.jar" }}
            - name: iotdb-ext-udf
              mountPath: {{ print "/iotdb/ext/udf/" ($path | replace "files/ext/udf/" "") }}
              subPath: {{ $path | replace "files/ext/udf/" "" | b64enc | replace "=" "-" }}
            {{- end }}
            {{- end }}
            {{- if (.Files.Glob "files/sbin/**.sh") }}
            {{ range $path, $bytes := .Files.Glob "files/sbin/**.sh" }}
            - name: iotdb-sbin-override
              mountPath: {{ print "/iotdb/sbin/" ($path | replace "files/sbin/" "") }}
              subPath: {{ $path | replace "files/sbin/" "" | b64enc | replace "=" "-" }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if (.Files.Glob "files/conf/**.properties") }}
        - name: iotdb-conf-override
          configMap:
            name: {{ template "iotdb.fullname" . }}-conf-override-cm
        {{- end }}
        {{- if (.Files.Glob "files/conf/**.sh") }}
        - name: iotdb-conf-sh-override
          configMap:
            name: {{ template "iotdb.fullname" . }}-conf-sh-override-cm
            defaultMode: 0777
        {{- end }}
        {{- if (.Files.Glob "files/ext/udf/**.jar") }}
        - name: iotdb-ext-udf
          configMap:
            name: {{ template "iotdb.fullname" . }}-ext-udf-cm
        {{- end }}
        {{- if (.Files.Glob "files/sbin/**.sh") }}
        - name: iotdb-sbin-override
          configMap:
            name: {{ template "iotdb.fullname" . }}-sbin-override-cm
            defaultMode: 0777
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") .Values.nodeAffinity }}
      affinity:
        {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "{{ template "iotdb.fullname" . }}"
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
        {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - "{{ template "iotdb.fullname" . }}"
                topologyKey: {{ .Values.antiAffinityTopologyKey }}
        {{- end }}
        {{- with .Values.nodeAffinity }}
        nodeAffinity:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations  }}
        annotations:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{ toYaml .Values.dataVolumeClaimTemplate | nindent 8 }}
    - metadata:
        name: logs
        {{- with .Values.persistence.annotations  }}
        annotations:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{ toYaml .Values.logsVolumeClaimTemplate | nindent 8 }}
  {{- end }}
